"""Add new_table

Revision ID: 2227503255a6
Revises: 28bf47dd16b6
Create Date: 2024-05-29 17:10:59.084788

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '2227503255a6'
down_revision: Union[str, None] = '28bf47dd16b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
